package core

import (
	"strings"
	"testing"
)

func TestPhishletBuilder_Build(t *testing.T) {
	// Create mock analysis
	analysis := &HARAnalysis{
		Domains: map[string]*DomainInfo{
			"accounts.example.com": {
				OrigDomain:    "accounts.example.com",
				OrigSubdomain: "accounts",
				BaseDomain:    "example.com",
				IsLanding:     true,
				HasSession:    true,
			},
		},
	}

	// Mock selected cookies
	selectedCookies := []*CookieInfo{
		{
			Name:            "session_id",
			Domain:          ".accounts.example.com",
			HttpOnly:        true,
			Secure:          true,
			IsAuthCandidate: true,
		},
		{
			Name:            "auth_token",
			Domain:          ".example.com",
			HttpOnly:        true,
			Secure:          true,
			IsAuthCandidate: true,
		},
	}

	// Mock credentials
	credentials := &PostRequestInfo{
		UsernameKey: "email",
		PasswordKey: "password",
		PostType:    "json",
	}

	// Mock login info
	loginInfo := &PostRequestInfo{
		Domain: "accounts.example.com",
		Path:   "/api/auth/login",
	}

	// Build phishlet
	builder := NewPhishletBuilder(analysis, selectedCookies, credentials, loginInfo)
	yaml, err := builder.Build()
	if err != nil {
		t.Fatalf("Build failed: %v", err)
	}

	// Check generated YAML contains expected elements
	if !strings.Contains(yaml, "min_ver: '3.0.0'") {
		t.Error("Expected min_ver in YAML")
	}

	if !strings.Contains(yaml, "proxy_hosts:") {
		t.Error("Expected proxy_hosts section")
	}

	if !strings.Contains(yaml, "phish_sub: 'accounts'") {
		t.Error("Expected accounts subdomain in proxy_hosts")
	}

	if !strings.Contains(yaml, "domain: 'example.com'") {
		t.Error("Expected example.com domain in proxy_hosts")
	}

	if !strings.Contains(yaml, "session: true") {
		t.Error("Expected session: true")
	}

	if !strings.Contains(yaml, "is_landing: true") {
		t.Error("Expected is_landing: true")
	}

	if !strings.Contains(yaml, "auto_filter: true") {
		t.Error("Expected auto_filter: true")
	}

	if !strings.Contains(yaml, "auth_tokens:") {
		t.Error("Expected auth_tokens section")
	}

	if !strings.Contains(yaml, "session_id") {
		t.Error("Expected session_id in auth_tokens")
	}

	if !strings.Contains(yaml, "auth_token") {
		t.Error("Expected auth_token in auth_tokens")
	}

	if !strings.Contains(yaml, "credentials:") {
		t.Error("Expected credentials section")
	}

	if !strings.Contains(yaml, "key: 'email'") {
		t.Error("Expected email username key")
	}

	if !strings.Contains(yaml, "key: 'password'") {
		t.Error("Expected password key")
	}

	if !strings.Contains(yaml, "type: 'json'") {
		t.Error("Expected json type for credentials")
	}

	if !strings.Contains(yaml, "login:") {
		t.Error("Expected login section")
	}

	if !strings.Contains(yaml, "domain: 'accounts.example.com'") {
		t.Error("Expected login domain")
	}

	if !strings.Contains(yaml, "path: '/api/auth/login'") {
		t.Error("Expected login path")
	}

	// Check header comment
	if !strings.Contains(yaml, "# Generated by netter") {
		t.Error("Expected header comment")
	}
}
